### PR TITLE
CSS bug fixes (old)

### LINKED ISSUE #27: Home Page: Div Centering on Large Screens + Reorder Img Div
image

### LINKED ISSUE #31: Sponsorship Page: Text Alignment with Sponsors
image

### PR DESCRIPTION
**Pull request by annsudhart**
* (Sponsor page) Sponsor logo images now align with header (resolves #31)
* (Home page) ACM UCSD logo now appears on right side of home page (resolves #27) 
* (Home page) Centered div content above the fold for wider screens and iPad screen sizes (resolves #27) 
* (Events page) Aligned event header text with event cards

### CODE REVIEW

**Comment by leestanley** [comment]
Button spacing on the sponsorship page 
image

**Comment by leestanley** [comment]
Is there a way we can align each of the sponsorship logos vertically with each other? 
image

**Comment by leestanley** [comment]
Also oof can we revert the image placement to the left - the typing text keeps pushing the div on the right 
image

**Comment by annsudhart** [comment]
> Also oof can we revert the image placement to the left - the typing text keeps pushing the div on the right

I fixed it so that the typing text doesn't push the image to the right and we keep the image on the right, still wanna move the image back to the left?

**Comment by leestanley** [comment]
> > Also oof can we revert the image placement to the left - the typing text keeps pushing the div on the right
> 
> I fixed it so that the typing text doesn't push the image to the right and we keep the image on the right, still wanna move the image back to the left?

@annsudhart Oh yeah if we can keep it on the right so it matches the Figma that'd be great. There's still a slight layout issue with the buttons and the typing text here on my screen:

image

**Comment by sumeet-bansal** [comment]
@annsudhart can you put some space between the portal and diamond staff buttons on the About page?

**Comment by sumeet-bansal** [comment]
Nvm, it's just on this branch.

**Pull request closed without merging**
