### PR TITLE
Board Data Fetching

### PR DESCRIPTION
**Pull request by steets250**
This PR includes a JS-ported version of @meshachadoe's board sheet fetching script, and is able to be run by using `yarn run fetchBoard`. I want this to be a user-run event so that it's easier for us to notice any errors, rather than relying on the script in the event that a breaking change is made on the Google Sheet. I ran the script, so any new changes that have been made are also included.

### CODE REVIEW

**Comment by StormFireFox1** [comment]
Before I review this, I'm confused; I thought that our Board Spreadsheet is secure; if it is indeed secure and needs an account login, did we just commit credentials to version control?

**Comment by steets250** [comment]
Good point @StormFireFox1, I used the "Publish to the Web" functionality to allow access to the sheet via URL. That was an oversight, and I changed it to instead publish a specific sheet with only the public data from the current board sheet. This ensures that only the necessary data is accessible.

**Comment by StormFireFox1** [comment]
You might want to rebase, remove the secret URL, force push and allow GC to purge the old URL to maintain security.

**Comment by steets250** [comment]
The old URL: https://docs.google.com/spreadsheets/d/e/2PACX-1vQwZzdPyMYxxJF-9FZMLxis3Raq3ZqhWO28kEFhbO6HYtPqV7YvcX8h0GYmr35Is9tCHjCwA06RkoRr/356415068 is non-functional. You have to specifically publish a sheet in order for it to be accessible, and in this case, the `21-22` sheet is no longer published. If you think it's still a good idea, I can remove it from the PR history.

**Comment by StormFireFox1** [comment]
If it's non-functional, it's like a revoked secret. We're good.

**Review by trulyronak — APPROVED** [review]
lgtm

**Comment by steets250** [comment]
Thanks boss

**Pull request merged**
