### PR TITLE
Fixed button sizing on mobile

### LINKED ISSUE #42: Home Page: Button sizing on mobile +Match Figma
## Current:
image

## Figma:
image

### PR DESCRIPTION
**Pull request by bamkho4**
I want dev team offer by next week.

Resolves #42

### CODE REVIEW

**Comment by leestanley** [comment]
Buttons a bit tiny - can increase height and add a drop shadow like in the figma

Figma: 
image

PR:
image

**Comment by StormFireFox1** [comment]
Task linked: [CU-8gk44r Match home buttons with Figma design](https://app.clickup.com/t/8gk44r)

**Comment by steets250** [comment]
Going to wait for #61 to be merged before modifying any more CSS.

**Comment by leestanley** [comment]
so thiny tho compared to the current site 
image

**Pull request closed without merging**
