### PR TITLE
added website link previews using meta tags.

### PR DESCRIPTION
**Pull request by abhirajthakur**
Solution of issue #182

### CODE REVIEW

**Comment by steets250** [comment]
@leestanley does this meet the specs you were intending for the issue, or did we want something more granular? Perhaps even if not, this can get merged as an improvement of what's there currently.

**Review by trulyronak — APPROVED** [review]
This solves our problem for now - we'll be handling more robust meta tags with the prospect Next rewrite, but this will work for now

**Review by trulyronak — CHANGES_REQUESTED** [review]
Putting this on hold temporarily actually - testing on discord and I'm not able to see the previews (unsure if this is a Netlify issue though)
Screen Shot 2022-02-03 at 3 30 01 PM

**Comment by trulyronak** [comment]
Thank you for your contribution @abhirajthakur ! We'll see how we can best fit this PR into the codebase

**Comment by duanwilliam** [comment]
it might need a regular meta description tag as well. but yea we can prob just properly handle all the meta tags (title, description, og, twitter, etc) in the next rewrite

**Pull request closed without merging**
