### PR TITLE
Update BoardAPI.ts

### PR DESCRIPTION
**Pull request by farisashai**
# Description

Fixes a small bug (preventing website from building) where team is undefined if its blank in a row and we try to treat it as a string

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Logistical Change (something about code process / a readme change / documentation update)
- [ ] CI Change (relating to deployment / continuous integration)
- [ ] Something Else 

# How Has This Been Tested?
- [x] Tested on Localhost (Desktop)
- [x] Tested on Localhost (Mobile) - use https://ngrok.io to get a copy on a mobile device
- [x] Tested on Deployed Preview (Desktop)
- [x] Tested on Deployed Preview (Mobile)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code as needed, particularly in hard-to-understand areas
- [x] My changes generate no new warnings (if they do, please explain why)

### CODE REVIEW

**Comment by trulyronak** [comment]
When would we not have a team?

**Comment by farisashai** [comment]
> When would we not have a team?

if you look at the current spreadsheet [acmurl.com/board](https://acmurl.com/board) for 2022-23, apparently the team is undefined rather than an empty string for the blank rows which is causing the entire main website build to fail

**Comment by trulyronak** [comment]
OH you mean like its treating empty rows as undefined, gotcha (tho in this case we just shouldn't render them if they don't have a team)

**Review by trulyronak — APPROVED** [review]
lgtm

**Review by amberleehuynh — APPROVED** [review]
Nice work as well as the explanation for line 44.

**Pull request merged**
