### PR TITLE
Scrolling events

### PR DESCRIPTION
**Pull request by annsudhart**
Events are now horizontally scrollable, and shows a maximum of 6 events

Also upgraded the events api to v2

### CODE REVIEW

**Comment by leestanley** [comment]
wat 
image

**Comment by annsudhart** [comment]
> wat
> image

o shoot, let me see what's happening

**Comment by annsudhart** [comment]
Looks like there are still bugs in what I made, yikes. I'll let you know when it's fixed

**Comment by annsudhart** [comment]
Ready for review!

**Comment by leestanley** [comment]
Looks good - can you go into the pages/events/index.tsx and change the splicing from `0,6` to just
image
We can now load all of the events instead of just 6

**Review by eminguyen — APPROVED** [review]

**Pull request merged**
